# Generated by Django 4.2.1 on 2023-05-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('content', models.CharField(blank=True, default='', max_length=100000, null=True)),
                ('image', models.CharField(blank=True, default='', max_length=100000, null=True)),
            ],
        ),
    ]
