# Generated by Django 4.2.1 on 2023-05-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('otp', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
