# Generated by Django 4.2.1 on 2023-06-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('related_issue', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
        ),
    ]
